language: node_js
node_js:
  - 0.8

script: node_modules/karma/bin/karma start js-tdd/tests/karma.conf.js --single-run

before_install:
  - npm install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
